---
- hosts: localhost
  tasks:
  - name: Login to ocp
    shell: oc login https://api-int.lab.ocp.lan:6443 -u ecslab -p "{{ ecslab_passwd }}" --kubeconfig=ecslab-kubeconfig --insecure-skip-tls-verify
  - name: Get pods 
    shell: oc get pods --kubeconfig=ecslab-kubeconfig -n openshift-marketplace
    register: pod_status
  - name: pod output
    debug: 
     msg: "{{ pod_status }}"
  - name: pod status
    debug: 
     msg: "{{ pod_status.stdout }}"
  - name: get advance cluster management operator CSV status using json_query
    debug:
      msg: "{{ pod_status.stdout | from_json | json_query('items[*].status.containerStatuses[*].ready') }}"